name: yandex_to_do_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  bloc: ^8.1.4
  dio: ^5.4.3+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
    
  flutter_localizations: # Добавить эти
    sdk: flutter         # строки
  flutter_bloc: ^8.1.6
  intl: ^0.19.0
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  logger: ^2.3.0
  rxdart: ^0.28.0
  shared_preferences: ^2.2.3
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
  generate: true # Добавить эту строку
#  assets:

